
public void textfield1_change1(GTextField source, GEvent event) {
}

public void button1_click1(GButton source, GEvent event) {
  q = definitePrime(2048, rnd);
  p = definitePrime(2048, rnd);
  n = p.multiply(q);
  totn = (p.subtract(one)).multiply(q.subtract(one)); 
  e = coPrime(2048, rnd);
  d = e.modInverse(totn);
  String E = "" + e;
  String N = "" + n;
  String D = "" + d;
  textfield2.setText(E);
  textfield3.setText(N);
  textfield4.setText(D);
  println("q: " + q);
  println("p: " + p);
  println("n: " + n);
  println("e: " + e);
  println("d: " + d);
}

public void textfield2_change1(GTextField source, GEvent event) {
}

public void textfield3_change1(GTextField source, GEvent event) {
}

public void button2_click1(GButton source, GEvent event) {
  BigInteger result;
  String in1;
  String ie1;
  String pt1;
  pt1 = trim(textfield1.getText());
  ie1 = trim(textfield2.getText());
  in1 = trim(textfield3.getText());
  BigInteger le = new BigInteger(ie1);
  BigInteger ln = new BigInteger(in1);
  BigInteger pt = compress(pt1.toLowerCase());
  result = pt.modPow(le, ln);
  println("Encrypted: " + result);
}

public void textfield4_change1(GTextField source, GEvent event) {
} 

public void button3_click1(GButton source, GEvent event) {
  BigInteger result;
  String id1;
  String ct1;
  String in1;
  in1 = trim(textfield3.getText());
  id1 = trim(textfield4.getText());
  ct1 = trim(textfield1.getText());
  BigInteger in = new BigInteger(in1);
  BigInteger ld = new BigInteger(id1);
  BigInteger ct = new BigInteger(ct1);
  result = ct.modPow(ld, in);
  println(decompress(result));
}

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:354895:
  String [] toSave = new String [3];
  toSave[0] = "E: " + e;
  toSave[1] = "N: " + n;
  toSave[2] = "D: " + d;
  saveStrings("Numbers.txt" , toSave);
} //_CODE_:button4:354895:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  textfield1 = new GTextField(this, 100, 40, 100, 30, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  label1 = new GLabel(this, 115, 10, 70, 20);
  label1.setText("Text");
  label1.setOpaque(false);
  label2 = new GLabel(this, 10, 100, 80, 20);
  label2.setText("e");
  label2.setOpaque(false);
  button1 = new GButton(this, 95, 180, 110, 30);
  button1.setText("Generate n, e, and d");
  button1.addEventHandler(this, "button1_click1");
  textfield2 = new GTextField(this, 10, 130, 80, 30, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  textfield3 = new GTextField(this, 110, 130, 80, 30, G4P.SCROLLBARS_NONE);
  textfield3.setOpaque(true);
  textfield3.addEventHandler(this, "textfield3_change1");
  label3 = new GLabel(this, 110, 100, 80, 20);
  label3.setText("n");
  label3.setOpaque(false);
  button2 = new GButton(this, 95, 220, 110, 30);
  button2.setText("Encrypt");
  button2.addEventHandler(this, "button2_click1");
  textfield4 = new GTextField(this, 210, 130, 80, 30, G4P.SCROLLBARS_NONE);
  textfield4.setOpaque(true);
  textfield4.addEventHandler(this, "textfield4_change1");
  label4 = new GLabel(this, 210, 100, 80, 20);
  label4.setText("d");
  label4.setOpaque(false);
  button3 = new GButton(this, 95, 260, 110, 30);
  button3.setText("Decrypt");
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 0, 280, 50, 20);
  button4.setText("Save");
  button4.addEventHandler(this, "button4_click1");
}

// Variable declarations 
// autogenerated do not edit
GTextField textfield1; 
GLabel label1; 
GLabel label2; 
GButton button1; 
GTextField textfield2; 
GTextField textfield3; 
GLabel label3; 
GButton button2; 
GTextField textfield4; 
GLabel label4; 
GButton button3; 
GButton button4; 
